### ISSUE TITLE
3- Symptômes

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#10]
l. 1: "reproduire ses" --> "reproduire des"
items : ajouter des ";" en fin d'item
item 2: "et oui" --> "hé oui" ou "he oui"

Sect. 3.5, l.1: "lien la détection" --> "lien entre la détection"

**Comment by sabrinagranger** [comment]
l. 1: "reproduire ses" --> "reproduire des" : fait
items : ajouter des ";" en fin d'item : ok
item 2: "et oui" --> "hé oui" ou "he oui" : fait, "hé oui"
Sect. 3.5, l.1: "lien la détection" --> "lien entre la détection" : --> "montrer un lien entre la délétion d'un gène chez la souris et la survenue de problèmes neurolocomoteurs. "
