### ISSUE TITLE
4 - Acquisition

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#11]
Sect. 4.3: "en utilisant...autre)." --> "en utilisant leur définition métrologique."

Sect. 4.4, last item: "effacer" --> "effacer ou affecter"

**Comment by sabrinagranger** [comment]
Sect. 4.3: "en utilisant...autre)." --> "en utilisant leur définition métrologique." : fait

Sect. 4.4, last item: "effacer" --> "effacer ou affecter" : ajout fait
