### ISSUE TITLE
5 - Gestion des données

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#12]
Sect. 5.1, fin du 2eme par.: "besoin de ces données manquantes" --> "besoin, à une étape ultérieure, de ces données."

Sect. 5.4, 2eme par.: "stocker" --> "stocker ou transmettre"

**Comment by sabrinagranger** [comment]
Sect. 5.1, fin du 2eme par.: "besoin de ces données manquantes" --> "besoin, à une étape ultérieure, de ces données." : fait

Sect. 5.4, 2eme par.: "stocker" --> "stocker ou transmettre" : fait
