### ISSUE TITLE
7 - Communication

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#15]
Sect. 7.3: ajouter ref en fin de 1er par. (autocitation honteuse..., mais pertinente)
@Article{Hebrard2009,
  Title                    = {How measurements of rate coefficients at low temperature increase the predictivity of photochemical models of {Titan}'s atmosphere},
  Author                   = {H\'ebrard, E and Pernot, P and Dobrijevic, M and Carrasco, N and Bergeat, A and Hickson, K M and Canosa, A and Picard, S D Le and Sims, I R},
  Journal                  = {J. Phys. Chem. A},
  Year                     = {2009},
  Pages                    = {11227--11237},
  Volume                   = {113},
  Doi                      = {10.1021/jp905524e},
}

* Sect. 7.4: ajouter une virgule après (Chapitre 11)

**Comment by sabrinagranger** [comment]
Sect. 7.3: ajouter ref en fin de 1er par. (autocitation honteuse..., mais pertinente)
@Article{Hebrard2009,
Title = {How measurements of rate coefficients at low temperature increase the predictivity of photochemical models of {Titan}'s atmosphere},
Author = {H'ebrard, E and Pernot, P and Dobrijevic, M and Carrasco, N and Bergeat, A and Hickson, K M and Canosa, A and Picard, S D Le and Sims, I R},
Journal = {J. Phys. Chem. A},
Year = {2009},
Pages = {11227--11237},
Volume = {113},
Doi = {10.1021/jp905524e},
}
: fait (formatage après)
Sect. 7.4: ajouter une virgule après (Chapitre 11) : fait
