### ISSUE TITLE
8 - Le temps...

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#16]
* Sect. 8.1: ajouter ref après "délicat".
@article {Barba142,
	author = {Barba, Lorena A.},
	title = {The hard road to reproducibility},
	volume = {354},
	number = {6308},
	pages = {142--142},
	year = {2016},
	doi = {10.1126/science.354.6308.142},
	publisher = {American Association for the Advancement of Science},
	issn = {0036-8075},
	URL = {https://science.sciencemag.org/content/354/6308/142},
	eprint = {https://science.sciencemag.org/content/354/6308/142.full.pdf},
	journal = {Science}
}

* Sect 8.1: new paragraph après "vide)."

* Sect. 8.1: mauvais formatage de la liste

* Sect 8.1: "cherry picking proof" --> "cherry-picking-proof" + donner une ref.

**Comment by sabrinagranger** [comment]
Sect. 8.1: ajouter ref après "délicat".
@Article {Barba142,
author = {Barba, Lorena A.},
title = {The hard road to reproducibility},
volume = {354},
number = {6308},
pages = {142--142},
year = {2016},
doi = {10.1126/science.354.6308.142},
publisher = {American Association for the Advancement of Science},
issn = {0036-8075},
URL = {https://science.sciencemag.org/content/354/6308/142},
eprint = {https://science.sciencemag.org/content/354/6308/142.full.pdf},
journal = {Science}
}
ok
Sect 8.1: new paragraph après "vide)." : ok

Sect. 8.1: mauvais formatage de la liste : pb ; s'affiche correctement sur l'interface web mais pb en pdf

Sect 8.1: "cherry picking proof" --> "cherry-picking-proof" + donner une ref.
