### ISSUE TITLE
9 - Documenter

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#17]
* Sect. 9.3: Nouveau par. avant "Le tableur"

* Sect. 9.5: problème de formulation des liens à cliquer pour la version imprimée.
"aller sur le site du CNRS ici" --> "consulter le sire du CNRS"
"vous pouvez cliquer ici" --> " vous pouvez consulter le document ..."

**Comment by sabrinagranger** [comment]
Sect. 9.3: Nouveau par. avant "Le tableur" : fait

Sect. 9.5: problème de formulation des liens à cliquer pour la version imprimée.
"aller sur le site du CNRS ici" --> "consulter le sire du CNRS"
"vous pouvez cliquer ici" --> " vous pouvez consulter le document ..." : fait
