### ISSUE TITLE
10 - Formater

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#18]
* Sect. 10.1, par. 1: "sur laquelle ils" --> "qu'ils"
* Sect. 10.1, par. 3: "les aleas de la vie" ???
* Sect. 10.1, par. 4: "de la relation" --> "du lien"
* Sect. 10.1, par. 4: "données" --> "données archivées"

* Sect. 10.2: ponctuation de la liste
* Sect. 10.2: "et tenter de s'assurer" --> "et s'assurer"
* Sect. 10.2, liste 2, item 2: "les formats illisibles" --> "les formats codés, illisibles" + virgule après "pdf)"
* Sect. 10.2, liste 2, item 3: "tables" --> "tableaux"
* Sect. 10.2, avant der. par.: "Dans un tel cas" --> "Dans ce cas"

* Sect. 10.3.1: préciser "arbitraire" (Boris ?)

* Sect. 10.3.2: Au début du 2eme par, ajouter: "L'incertitude peut servir de guide pour choisir le nombre de chiffres significatifs".
* Sect. 10.3.2: "On évitera" --> "En outre, on évitera"
* Sect. 10.3.2: pb de polices pour les nombres. Supprimet le code latex pour les 2 derniers.

**Comment by sabrinagranger** [comment]
Sect. 10.1, par. 1: "sur laquelle ils" --> "qu'ils"
reformulation complète : "Le plus souvent, les chercheurs travaillent en fait sur une "collection" de données liées les unes aux autres. La relation entre ces données est essentielle. "

Sect. 10.1, par. 3: "les aleas de la vie" ??? reformulation pour explicitation de l'exemple développé
"Un autre exemple de structure est celui d'un arbre généalogique. Au prime abord, il semblerait naturel d'utiliser une "hiérarchie", mais la vie étant faite de surprises, cette représentation va rapidement s'avérer inadaptée pour concevoir un arbre généalogique clair."

Sect. 10.1, par. 4: "de la relation" --> "du lien" : fait

Sect. 10.1, par. 4: "données" --> "données archivées" : fait

Sect. 10.2: ponctuation de la liste : fait

Sect. 10.2: "et tenter de s'assurer" --> "et s'assurer" : fait

Sect. 10.2, liste 2, item 2: "les formats illisibles" --> "les formats codés, illisibles" + virgule après "pdf)" : fait

Sect. 10.2, liste 2, item 3: "tables" --> "tableaux" : fait

Sect. 10.2, avant der. par.: "Dans un tel cas" --> "Dans ce cas" : fait

Sect. 10.3.1: préciser "arbitraire" (Boris ?) : KO

Sect. 10.3.2: Au début du 2eme par, ajouter: "L'incertitude peut servir de guide pour choisir le nombre de chiffres significatifs". ok

Sect. 10.3.2: "On évitera" --> "En outre, on évitera" : fait

Sect. 10.3.2: pb de polices pour les nombres. Supprimet le code latex pour les 2 derniers. : KO

**Comment by alegrand** [comment]
Par les "aléas de la vie", je faisais référence aux décès, divorces, re-mariages, mariages entre cousins, etc.

**Comment by borishejblum** [comment]
Sect. 10.3.2: pb de polices pour les nombres. Supprimer le code latex pour les 2 derniers : fait
Sect. 10.3.1: préciser "arbitraire" : @alegrand  ?

**Comment by alegrand** [comment]
"arbitraire". Meuh, c'était pas moi, c'est @ppernot! Je dirais: Les calculs numériques sont effectués avec une précision finie ?

**Comment by borishejblum** [comment]
Mmm... je pense que je suis en réalité à l'origine de cet "précision arbitraire". J'avais en tête les tolérances numériques propre à chaque sytème/logiciel et la précision (simple, double ou quadruple) pouvant être utilisée. 
Mais en effet, "précision finie" ou "précision donnée" ou "précision déterminée" ou "précision fixée" sont surement des termes plus approriés. Ma préféence va à la proposition d' @alegrand ("précision finie") mais je laisse @sabrinagranger choisir.

**Comment by sabrinagranger** [comment]
"précision finie" : remplacé dans le texte
