### ISSUE TITLE
11 - Partager...

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#19]
* Sect. 11.2: ajouter après la 1ere phrase: "Il existe alors plusieurs façons de les mettre à disposition."

* Sect. 11.2.3: supprimer "ainsi"
* Sect. 11.2.3, item 2: "les exemples" --> "cf. les exemples"
* Sect. 11.2.3, item 3: "contrôlé" --> "contrôlée" 
* Sect. 11.2.3, item 3: "et ce" --> ", et ce,"
* Sect. 11.2.3, item 3:  "il n'est donc pas" --> "il n'est pas"

**Comment by sabrinagranger** [comment]
Sect. 11.2: ajouter après la 1ere phrase: "Il existe alors plusieurs façons de les mettre à disposition." fait

Sect. 11.2.3: supprimer "ainsi" : fait

Sect. 11.2.3, item 2: "les exemples" --> "cf. les exemples"
reformulation et changement d'ordre (exemples remontés en début d'item)
"La pérennité sur le long terme des outils comme des services n'est absolument pas garantie. On peut citer les cas de Gitorious et de Google Code, deux services d'hébergement de code. Leur popularité n'a pas empêché leur fermeture. En déléguant la  responsabilité du stockage à un hébergeur extérieur, vous prenez un risque conséquent. Vous pouvez utiliser ce type de service mais il faut absolument
  vous assurer que vous disposez d'une solution d'archivage en complément."
Sect. 11.2.3, item 3: "contrôlé" --> "contrôlée" : fait

Sect. 11.2.3, item 3: "et ce" --> ", et ce," : fait

Sect. 11.2.3, item 3: "il n'est donc pas" --> "il n'est pas" : fait
