### ISSUE TITLE
13 - Apprendre...

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#21]
* Sect. 13.1: changement de par. avent "Ce type"
* Sect. 13.1, par. 2: " Ce type d'interface...aussi" --> "On le trouve aussi dans de nombreux logiciels scientifiques"
* Sect. 13.1, par. 3, fin: "tenez à jour un cahier de laboratoire" --> "tenez scrupuleusement à jour votre cahier de laboratoire"

* Sect. 13.2, 1st sentence: "faire." --> "faire faire à au logiciel."
* Sect. 13.2: pb. repliement des commentaires du code. Déclarer une largeur plus petite dans les options de R ???
* Sect. 13.2, liste: "il effectue les traitements" --> "il effectue les traitements de manière reproductible"

**Comment by sabrinagranger** [comment]
Sect. 13.1: changement de par. avent "Ce type"
fait
Sect. 13.1, par. 2: " Ce type d'interface...aussi" --> "On le trouve aussi dans de nombreux logiciels scientifiques"
reformulation : "Dans de nombreux logiciels scientifiques, ce type d'interface est également disponible, 
par exemple pour traiter les données ou concevoir des figures. "

Sect. 13.1, par. 3, fin: "tenez à jour un cahier de laboratoire" --> "tenez scrupuleusement à jour votre cahier de laboratoire" : fait

Sect. 13.2, 1st sentence: "faire." --> "faire faire à au logiciel." fait

Sect. 13.2: pb. repliement des commentaires du code. Déclarer une largeur plus petite dans les options de R ???
non traité, ai vu mais ne sais pas faire
Sect. 13.2, liste: "il effectue les traitements" --> "il effectue les traitements de manière reproductible"
"Par rapport à Excel, le programme offre deux avantages majeurs : 

- d'une part, il effectue les traitements de manière reproductible,
- d'autre part, il documente cette chaîne de traitements, si bien que
  quiconque est maintenant en mesure de comprendre et de reproduire
  ces traitements, éventuellement à l'aide d'un autre de langage de
  programmation."

**Comment by alegrand** [comment]
Pour le code R qui déborde, ça n'a d'importance que pour le pdf que je vous ai envoyé (pour le HTML, on s'en fiche), sachant qu'Élisa va en refaire un de toutes façons. Je pense que c'est donc sans grande importance. Ça sera à discuter avec Élisa et il suffit de réécrire nos commentaires un peu différemment.
