### ISSUE TITLE
14 - Rendre...

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#22]
* intro, 1st sentence: renvoi Chapitre 8
* intro, 1st sentence: "de diffusion, de partage de ses" --> "de diffusion et de partage des"

* Sect. 14.2, l.1: "écrivant" --> "tapant" ou "saisissant"

* Sect. 14.3 : p. repli des commentaires du code

* Sect. 14.4, last line: "retrouver" --> "retrouver simultanément"

* Sect. 14.5, 3eme liste, item 2: introduire un nouvel item à "Enfin"

* pb. repliement URL en footnote 7

**Comment by sabrinagranger** [comment]
intro, 1st sentence: renvoi Chapitre 8
pas fait
intro, 1st sentence: "de diffusion, de partage de ses" --> "de diffusion et de partage des": fait

Sect. 14.2, l.1: "écrivant" --> "tapant" ou "saisissant" : fait

Sect. 14.3 : p. repli des commentaires du code

Sect. 14.4, last line: "retrouver" --> "retrouver simultanément" : fait

Sect. 14.5, 3eme liste, item 2: introduire un nouvel item à "Enfin"
ok - d'une part ils permettent une meilleure transparence du code 
effectivement exécuté,
- d'autre part, ils facilitent sa compréhension car le code devient une partie intégrante d'une trame narrative ; certains *notebooks* peuvent ainsi quasiment s'apparenter à des articles,
- enfin, ces documents peuvent répondre à des besoins de traçabilité en raison de leur caractère dynamique : on obtient en effet des cellules de codes prototypes qu'il est possible de réécrire et de réexécuter avec des paramètres différents.  

pb. repliement URL en footnote 7
