### ISSUE TITLE
17 - Sortez...

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#24]
* Sect. 17.1: "Que soit" --> "Que ce soit"

* Sect. 17.2:  " pour: - des raison éthiques,..." --> "pour des raisons: -éthiques,..." et déplier la liste

* Sect. 17.3: c'est un peu le b...l. Créer une liste et virer la toc des vdéos...

**Comment by sabrinagranger** [comment]
Sect. 17.1: "Que soit" --> "Que ce soit"
reformulation : 
"Qu'il s'agisse de données ou de code, l'utilisation d'une licence facilite la spécification des conditions dans lesquelles se fait le partage. "

Sect. 17.2: " pour: - des raison éthiques,..." --> "pour des raisons: -éthiques,..." et déplier la liste
ok affichage web, ko pdf :\

Sect. 17.3: c'est un peu le b...l. Créer une liste et virer la toc des vdéos...
maxima culpa ; ai prévu de tout toiletter au moment de la biblio
suppr liste des chapitres intervention ok
