### ISSUE TITLE
18 - Annexes

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#25]
* Sect. 18.1: Mettre la definition du book sprint en footnote ?

* Sect. 18.2: "forme trandirionnelle du book sprint": donner une réf ?
* Sect. 18.2: "FlossManuals": donner un lien
* Sect. 18.3, last list: "droit de paternité" ou "droit de propriété" ??? + new item avant "le livrable" ?
* Sect. 18.3, last sentence. ". la" --> ". La" + manque le point final.

**Comment by sabrinagranger** [comment]
Sect. 18.1: Mettre la definition du book sprint en footnote ?

Sect. 18.2: "forme trandirionnelle du book sprint": donner une réf ?
Baker, Rachel, David Berry, Mark Brokering, Michael Dieter, Amanda French, and Barbara Rühling. 2014. On Book Sprints. Berlin: Booksprints.net. https://www.booksprints.net/en/blog/book-sprint-on-book-sprints/.

Sect. 18.2: "FlossManuals": donner un lien ; 
fait
Sect. 18.3, last list: "droit de paternité" ou "droit de propriété" ??? + new item avant "le livrable" ?
reformulation : "le droit de paternité (au sens du code de la propriété intellectuelle)"
ajout ponctuation qui manquait avait "le livrable"
Sect. 18.3, last sentence. ". la" --> ". La" + manque le point final. fait
