### ISSUE TITLE
Portraits

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#26]
* "Qui sont nos auteurs" --> "Qui sont-ils ?"

* Loïc
    + "Ecole nationale vétérinaire" --> "Ecole Nationale Vétérinaire"
    + new paragraph avant "Il travaille" ?
    + "article" --> "articles"

* Boris
    + new paragraph avant "Il travaille" ?

* Arnaud
    + "l'axe optimisation" : késako ?

* Pascal
    + pour uniformiser: "Physico-chimiste et directeur de recherches au CNRS, Pascal Pernot travaille au Laboratoire de Chimie Physique à l'Université Paris-Sud.

* Nicolas
    + pour uniformiser: "Chercheur à  Inria, Nicaloas Rougier est membre..."

* Sabrina
     + c'est le souk: "Conservateur des biblios,..., S. Granger est conservateur des biblios."

**Comment by sabrinagranger** [comment]
"Qui sont nos auteurs" --> "Qui sont-ils ?"
fait
Loïc

"Ecole nationale vétérinaire" --> "Ecole Nationale Vétérinaire"
new paragraph avant "Il travaille" ?
"article" --> "articles"
tout fait ok
Boris

new paragraph avant "Il travaille" ?
Arnaud

"l'axe optimisation" : késako ?
euh, ai tenté : "L’axe optimisation de ses travaux porte sur la proposition ou l’évaluation de méthodes 
souvent sophistiquées et où il est important de conserver 
tous les détails pour comprendre leur performance et
comment les améliorer."
Pascal

pour uniformiser: "Physico-chimiste et directeur de recherches au CNRS, Pascal Pernot travaille au Laboratoire de Chimie Physique à l'Université Paris-Sud.
fait
Nicolas

pour uniformiser: "Chercheur à Inria, Nicaloas Rougier est membre..."
fait 

Sabrina

c'est le souk: "Conservateur des biblios,..., S. Granger est conservateur des biblios."
corrigé
