### ISSUE TITLE
9 - Documenter ; ref HAL introuvable

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#29]
chap 9, "pour en savoir plus"
un nom d'auteur svp? 
Le document avec l'identifiant hal-02103716 n'existe pas. 
https://hal.archives-ouvertes.fr/hal-02103716

**Comment by alegrand** [comment]
Je pense que c'est le document que Loïc a déposé sur HAL pour disposer d'une URL plus pérene que [celle de wix](https://wixlabs-pdf-dev.appspot.com/assets/libs/pdfjs/web/viewer.html?file=%2Fpdfproxy%3Finstance%3DKDf9L508Xn2xJRMJOWyZswoWY30CfsoKGHjB8T131xQ.eyJpbnN0YW5jZUlkIjoiOTQ0MWMzYzItMzdhNC00NDk4LWEzNmUtM2I3MjA4OTQ2MWMyIiwiYXBwRGVmSWQiOiIxM2VlMTBhMy1lY2I5LTdlZmYtNDI5OC1kMmY5ZjM0YWNmMGQiLCJtZXRhU2l0ZUlkIjoiNzcwMDgzYTgtN2ZjMy00ODA3LTk0NDctMTQ0MGEyODAxZWIwIiwic2lnbkRhdGUiOiIyMDE5LTA0LTE4VDEzOjI4OjE0Ljc0MloiLCJ1aWQiOm51bGwsImlwQW5kUG9ydCI6Ijg2LjIzNC41Mi4yMy82MDM1MiIsInZlbmRvclByb2R1Y3RJZCI6bnVsbCwiZGVtb01vZGUiOmZhbHNlLCJhaWQiOiI4Y2QwNzMzNi1jYzIwLTQ4YzMtYjEzZC0wMDI4YTU4ODMyMDQiLCJiaVRva2VuIjoiZTM0MTQwNmEtNDg2Ny0wYzlmLTM3MjktMmYzMmFhMTQ3ZjcyIiwic2l0ZU93bmVySWQiOiI2MDJhNTdiNy05NGEwLTQ3OGMtODQxNC1iNzg1NGRlNDliYmMifQ%26compId%3Dcomp-jto1zpdt%26url%3Dhttps%3A%2F%2Fdocs.wixstatic.com%2Fugd%2F602a57_1db4a443deb04b31b7af42d1a5aef9ed.pdf#page=1&links=true&originalFileName=Concordance%20sur%20series%20mesures%20v12.7&allowDownload=true&allowPrinting=true). Peut-être est-il encore en attente de validation. Loïc a p-e reçu un mail à ce sujet...

**Comment by sabrinagranger** [comment]
merci Arnaud, je vais pouvoir le créer quand même dans Zotero 
je commence à voir le bon bout ; j'intègre les sites web avec les autres réfs pour que le listing final soit exhaustif 

--- 
Sabrina Granger 


Conservateur des bibliothèques 
Co-responsable, référent axe "Information scientifique et technique" 
--- 
Unité régionale de formation à l'information scientifique et technique 
16 avenue Léon Duguit - Bureau F38B (RDC) - CS 50057 - 33608 PESSAC CEDEX 


+33 5 56 84 86 93/86 97 


[ http://weburfist.univ-bordeaux.fr/wp-content/uploads/2017/10/Plan-du-campus-avec-les-nouveaux-locaux-Urfist.pdf | Localiser la salle de formation et les bureaux de l'Urfist ] 


[ http://weburfist.univ-bordeaux.fr/ | Site web de l'Urfist ] / [ https://twitter.com/urfistbordeaux | Suivre la veille de l'Urfist sur Twitter ] 


Référent pédagogique, administratif et financier : 


[ mailto:isabelle.scarpat-bouvet@u-bordeaux.fr | isabelle.scarpat-bouvet@u-bordeaux.fr ] / +33 5 56 84 85 85 




De: "Arnaud Legrand" <notifications@github.com> 
À: "alegrand/bookrr" <bookrr@noreply.github.com> 
Cc: "Sabrina Granger" <sabrina.granger@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 30 Avril 2019 11:42:03 
Objet: Re: [alegrand/bookrr] 9 - Documenter ; ref HAL introuvable (#29) 



Je pense que c'est le document que Loïc a déposé sur HAL pour disposer d'une URL plus pérene que [celle de wix]( [ https://wixlabs-pdf-dev.appspot.com/assets/libs/pdfjs/web/viewer.html?file=%2Fpdfproxy%3Finstance%3DKDf9L508Xn2xJRMJOWyZswoWY30CfsoKGHjB8T131xQ.eyJpbnN0YW | https://wixlabs-pdf-dev.appspot.com/assets/libs/pdfjs/web/viewer.html?file=%2Fpdfproxy%3Finstance%3DKDf9L508Xn2xJRMJOWyZswoWY30CfsoKGHjB8T131xQ.eyJpbnN0YW ] 
5jZUlkIjoiOTQ0MWMzYzItMzdhNC00NDk4LWEzNmUtM2I3MjA4OTQ2MWMyIiwiYXBwRGVmSWQiOiIxM2VlMTBhMy1lY2I5LTdlZmYtNDI5OC1kMmY5ZjM0YWNmMGQiLCJtZXRhU2l0ZUlkIjoiNzcwMDgzYTgtN2ZjMy00ODA3LTk0ND 
ctMTQ0MGEyODAxZWIwIiwic2lnbkRhdGUiOiIyMDE5LTA0LTE4VDEzOjI4OjE0Ljc0MloiLCJ1aWQiOm51bGwsImlwQW5kUG9ydCI6Ijg2LjIzNC41Mi4yMy82MDM1MiIsInZlbmRvclByb2R1Y3RJZCI6bnVsbCwiZGVtb01vZGUiOm 
ZhbHNlLCJhaWQiOiI4Y2QwNzMzNi1jYzIwLTQ4YzMtYjEzZC0wMDI4YTU4ODMyMDQiLCJiaVRva2VuIjoiZTM0MTQwNmEtNDg2Ny0wYzlmLTM3MjktMmYzMmFhMTQ3ZjcyIiwic2l0ZU93bmVySWQiOiI2MDJhNTdiNy05NGEwLTQ3OG 
MtODQxNC1iNzg1NGRlNDliYmMifQ%26compId%3Dcomp-jto1zpdt%26url%3Dhttps%3A%2F%2Fdocs.wixstatic.com%2Fugd%2F602a57_1db4a443deb04b31b7af42d1a5aef9ed.pdf#page=1&links=true&originalFil 
eName=Concordance%20sur%20series%20mesures%20v12.7&allowDownload=true&allowPrinting=true). Peut-être est-il encore en attente de validation. Loïc a p-e reçu un mail à ce sujet...

**Comment by sabrinagranger** [comment]
Desquilbet, Loïc. 2019. ‘Guide Pratique de Validation Statistique de Méthodes de Mesure : Répétabilité, Reproductibilité, et Concordance’. Maison Alfort: Ecole Nationale Vétérinaire Maison Alfort. https://bit.ly/2ZKcQGL.

**Comment by borishejblum** [comment]
@loicdesquilbet des nouvelles de ta soumission HAL ?

**Comment by sabrinagranger** [comment]
@loicdesquilbet si tu n'as pas de bibliothécaire sous la main, voici le mail du service question-réponses de HAL hal.support@ccsd.cnrs.fr 
ils répondent rapidement et en langage compréhensible pour les humains ; je px aussi pêcher des infos si tu me donnes des compléments
