### ISSUE TITLE
biblio finale (my precious)

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#36]
[20190430_Biblio_booksprint.pdf](https://github.com/alegrand/bookrr/files/3131236/20190430_Biblio_booksprint.pdf)

chicago manual of style 17 th ed. full note

**Comment by sabrinagranger** [comment]
biblio au format .bib
https://framadrive.org/s/58n56Q3q3qt42Qk

**Comment by sabrinagranger** [comment]
format pdf de la version la + récente
[20190430_Biblio_booksprint3.pdf](https://github.com/alegrand/bookrr/files/3131908/20190430_Biblio_booksprint3.pdf)

**Comment by sabrinagranger** [comment]
https://framadrive.org/s/3Qz7y9oYmmZJTJR

**Comment by sabrinagranger** [comment]
https://framadrive.org/s/GMay58rW5Xyreor

**Comment by sabrinagranger** [comment]
https://framadrive.org/s/63fSHtdQFYAPA8G
2 entrées supplémentaires par rapport à la V1 du 2019/05/03

**Comment by sabrinagranger** [comment]
https://framadrive.org/s/8HftEPjFef3EHXJ 
champ ed nettoyé pour ref Chacon
par contre, pb avec ref Baker, Monya. ‘1,500 Scientists Lift the Lid on Reproducibility’. Nature News 533, no. 7604 (26 May 2016): 452. https://doi.org/10.1038/533452a.
non exportée apparemment

**Comment by sabrinagranger** [comment]
dont ref à Baker 2016
https://framadrive.org/s/QQze55itW2bmL6X

**Comment by alegrand** [comment]
Normalement, plus besoin de passer par framadrive. Maintenant que c'est intégré à CI, toutes les petites modifications nécessaires sur le .bib sont faites juste avant de compiler.

**Comment by sabrinagranger** [comment]
sait-on jms
@alegrand 
https://framadrive.org/s/agJa4j2e6844Zop 

hey, ce serait sympa de mettre à disposition le fichier des refs pour que les gens puissent le télécharger dir dans leur gestionnaire de refs? 
le fichier en .ris
https://framadrive.org/s/9Fkfi32SCnJ7DNT 

où on pourrait mettre ça? au début du chap biblio? avec le petit tuto qui va bien https://carrefour.uquebec.ca/zotero/importer-references-partir-dun-fichier-ris

**Comment by sabrinagranger** [comment]
liens intégrés chap biblio
