### ISSUE TITLE
Refs biblios sous paywall : proposition

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#38]
les refs biblios dont le texte n'est pas en accès libre sont très minoritaires dans la biblio ; ce serait dommage de supprimer ces infos

quand c'étt possible, j'ai mis un lien vers un équivalent (Pascal avait par ex indiqué le rapport technique de Collberg) en plus de la réf
j'ai complété les refs pour certains chapitres

proposition : (à mettre en entête de la biblio finale?)
inviter les lecteurs qui voudraient accéder aux full texts à se rapprocher de leur bibliothèque ; leurs structures sont peut-être abonnées ; il y a la poss de faire une demande de prêt entre bibliothèques (service devenu gratuit dans certaines universités), etc.

on peut aussi signaler ces sites pour la recherche de la version en libre accès d’un article

    oaDOI https://oadoi.org/
    Unpaywall http://unpaywall.org/
    Scilit https://www.scilit.net/  moissonnage quotidien de CrossRef et PubMed et repérage des articles librement accessibles, basé sur les informations de licence au niveau de l’article, grâce à Unpaywall et au réservoir CORE. Outil développé et maintenu par l’éditeur MDPI. Chiffres donnés le 25 mai 2018 : 20 millions d’articles en libre accès sur 110 millions d’article signalés.

**Comment by sabrinagranger** [comment]
infos intégrées début chap 18

**Comment by rougier** [comment]
Sinon y'a les liens sci-hub...

**Comment by sabrinagranger** [comment]
t'es sérieux ?
![ultra_violence](https://user-images.githubusercontent.com/46864154/57154428-21911d80-6dd9-11e9-98bb-9dee8b86c1cb.jpg)

**Comment by sabrinagranger** [comment]
heureusement qu'on se connaît
