### ISSUE TITLE
Jenny Bryan gate : fixed? 

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#39]
pb de données biblios répercutées dans de mvs champs lors de l'export en .bib
ex Jenny Bryan "How to name files" : infos sur le talk toutes intégrées dans le champ "abstract" qui n'apparaît pas en biblio finale
ai vérifié toutes les refs du fichier .refs.bib : a priori ok avec l'export en bibtex au lieu de betterbibtex 
@unpublished{bryanHowNameFiles2015,
  venue = {{Duke}},
  title = {How to Name Files},
  url = {https://speakerdeck.com/jennybc/how-to-name-files},
  abstract = {Low-tech common sense about filenames. Prepared under the auspices of the Reproducible Science Curriculum (https://github.com/Reproducible-Science-Curriculum). Slides made for a workshop at Duke in May 2015.},
  eventtitle = {Reproducible {{Research Workshop}}},
  urldate = {2019-04-30},
  date = {2015-05-14},
  author = {Bryan, Jenny},
  file = {C:\\Users\\sgranger\\Zotero\\storage\\U6SFR7JQ\\how-to-name-files.html}

**Comment by sabrinagranger** [comment]
idem, pour le champ date des sites web ; la date de consultation n'apparaissait pas
avec le dernier export, elle est bien dans le champ "urldate"
@online{gitlabGitlabIN2P3,
  title = {Gitlab {{IN2P3}}},
  url = {https://gitlab.in2p3.fr/users/sign_in},
  abstract = {Gitlab IN2P3},
  journaltitle = {GitLab},
  urldate = {2019-04-30},
  author = {{Gitlab}},
  file = {C:\\Users\\sgranger\\Zotero\\storage\\XT4VH4FM\\sign_in.html}

**Comment by rougier** [comment]
Selon le style utilisé, y'a des chances que latex ajouter pas le consultation data. Au pire tu peux le mettre dans le champ `note`.

**Comment by alegrand** [comment]
Corrigé avec l'intégration à CI qui met un coup de sed dans le .bib avant de compiler
