### ISSUE TITLE
make html fails

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#43]
> Rscript -e "rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8')"
> 
> 
> processing file: booksprintrr.Rmd
>   |.................................................................| 100%
>    inline R code fragments
> 
> 
> output file: booksprintrr.knit.md
> 
> /usr/bin/pandoc +RTS -K512m -RTS booksprintrr.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output booksprintrr.html --smart --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --template /home/pernot/R/library/3.2/bookdown/templates/gitbook.html --highlight-style pygments --number-sections --css css/style.css --include-in-header /tmp/RtmpySOsiG/rmarkdown-str418f1ed4ad48.html --mathjax --filter pandoc-citeproc 
> pandoc: Filter pandoc-citeproc not found
> Erreur : pandoc document conversion failed with error 85
> Exécution arrêtée
> Error in render_book_script(output_format, envir, quiet) : 
>   Error 1 attempting to render book
> Calls: <Anonymous> -> <Anonymous> -> in_dir -> render_book_script
> Exécution arrêtée
> Makefile:21 : la recette pour la cible « html » a échouée
> make: *** [html] Erreur 1

**Comment by ppernot** [comment]
Solved by installing pandoc-citeproc

**Comment by ppernot** [comment]
Should this be mentioned in the install instructions ?

**Comment by alegrand** [comment]
Yes. Please, just do it. :)
