### ISSUE TITLE
pb affichage italique en pdf

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#46]
@alegrand pour certaines mentions ex. p 79 (14.4 documenter son code) le cf. apparaît en italique sur l'interface Github mais pas dans la sortie pdf (p. 79) du fichier ?? que faire
[20190503_booksprintrr2.pdf](https://github.com/alegrand/bookrr/files/3141720/20190503_booksprintrr2.pdf)

**Comment by ppernot** [comment]
il y a deux façons de faire des italiques `_ital_` ou `*ital*` 
L'une des deux n'est peut-être pas un standard md...

**Comment by sabrinagranger** [comment]
j'utilisais *ital*

**Comment by sabrinagranger** [comment]
les étoiles je vx dire (bravo le veau)
