### ISSUE TITLE
1.1 pb ref Baker non traitée alors que clé ok

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#47]
clé correcte [@baker500ScientistsLift2016]
ref présente dans le fichier .refs (adéquation avec la clé utilisée)
mais n'apparaît pas dans le pdf du 03/05/2019  :ni dans le corps de texte chap 01), ni dans la biblio finale

**Comment by sabrinagranger** [comment]
changement de clé suite à des pbs d'exports (ref non prise en compte dans l'export.bib alors que ok dans d'autres formats ou d'autres exports en .bib)
rectifié dans texte

**Comment by alegrand** [comment]
Semble OK dans le pdf actuellement sur CI.

**Comment by sabrinagranger** [comment]
traitée en effet mais comme un site web alors que le type de doc est bien "article " dans .refs
mais tant pis
