### ISSUE TITLE
un petit script biblio?

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#48]
@alegrand 
qui propose s'expose ... 
stp, penses-tu qu'il serait possible d'automatiser ceci pour les refs biblios? 
* au-delà du 10ème auteur, introduire la mention et al. en italique (ex de l'article "Justify your alpha" avec sa liste super longue idem pour la ref "The FAIR guiding principes .."
* pour les pages et sites web (je repds la typologie de Zotero), billets de blog --> mentionner entre crochets la date de consultation soit au format jj/mm/aaaa ou aaaa/mm/jj selon ce qui te semble le plus adapté à tous publics
* ne faire figurer que l'initiale du prénom des auteurs? pour qqs refs, je n'arrive pas à trouver le prénom des auteurs aussi strange que ça paraisse ; après, ça concerne 3 refs sur toute la biblio ; si ça choque personne, on peut laisser en l'état
sinon pour le style, je n'ai pas de préférence, pour ma part, nihil obstat avec celui-ci

**Comment by alegrand** [comment]
Oui. En fait, les points 1 et 3 se gèrent via le .bst. Il suffit de trouver un style de citation bst plus adapté (et en français tant qu'à faire). Pour le point 2, soit j'arrive à faire un .bst qui le fait ou bien il faut un petit script pour le rajouter dans le champs note. À faire asap.

**Comment by sabrinagranger** [comment]
ok merci à toi
je rame pour 1 ref : celle de Baker, M ... elle s'exporte sous d'autres formats, et impossible de l"'avoir avec l'export bibtex pour le moment 
super spookie ...
Baker, Monya. ‘1,500 Scientists Lift the Lid on Reproducibility’. Nature News 533, no. 7604 (26 May 2016): 452. https://doi.org/10.1038/533452a.
au pire ...

@article{baker500ScientistsLift2016,
	title = {1,500 scientists lift the lid on reproducibility},
	volume = {533},
	url = {http://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970},
	doi = {10.1038/533452a},
	abstract = {Survey sheds light on the ‘crisis’ rocking research.},
	language = {en},
	number = {7604},
	urldate = {2019-05-03},
	journal = {Nature News},
	author = {Baker, Monya},
	month = may,
	year = {2016},
	pages = {452},
	file = {Snapshot:C\:\\Users\\sgranger\\Zotero\\storage\\3A5FZEPQ\\1-500-scientists-lift-the-lid-on-reproducibility-1.html:text/html;Snapshot:C\:\\Users\\sgranger\\Zotero\\storage\\I2V5G9DP\\1-500-scientists-lift-the-lid-on-reproducibility-1.html:text/html}
}

fichier .bib de la ref récalcitrante
https://framadrive.org/s/5DzGn6MngPi6b2L

**Comment by sabrinagranger** [comment]
victory is mine !! après plusieurs essais bidouilles, la ref à baker 2016 est bien dans le nouvel export !

**Comment by sabrinagranger** [comment]
@alegrand 
ce n'est peut-être pas l'endroit mais je tente? 
pour faciliter la consultation des refs biblios de la version imprimée, serait-il possible de prévoir qq chose pour automatiser l'insertion des refs chap par chap en plus de la biblio finale stp? dans le pdf, c'est facile de naviguer mais pour un doc imprimé, ça peut devenir fastidieux

**Comment by rougier** [comment]
Pour la limite du `et al.` ca peut se gérer avec biber aussi:

```
\usepackage[natbib=true,
            style=numeric,
            sorting=ydnt,
            backend=biber,
            bibencoding=utf8,
            giveninits=true,
            url=false,
            doi=false,
            defernumbers,
            maxcitenames=10,
            defernumbers=true,
            maxbibnames=100]{biblatex}
\addbibresource{bibliographie.bib}
```

**Comment by sabrinagranger** [comment]
tout me va à partir du moment où on enlève le générique de star wars ; je vous laisse trancher

**Comment by alegrand** [comment]
Zut, j'avais pas vu la proposition de @rougier . Bon, j'ai trouvé une solution en tous cas, maintenant c'est bon, à la fois l'abréviation des prénoms et la limite sur le nombre d'auteurs.

**Comment by alegrand** [comment]
Salut,

Le 03/05/2019 à 15:44, Sabrina Granger a écrit :
> ce n'est peut-être pas l'endroit mais je tente?
> pour faciliter la consultation des refs biblios de la version imprimée,
> serait-il possible de prévoir qq chose pour automatiser l'insertion des
> refs chap par chap en plus de la biblio finale stp? dans le pdf, c'est
> facile de naviguer mais pour un doc imprimé, ça peut devenir fastidieux

Si j'ai bien compris, Elisa travaillera à partir de la version html
qu'on lui fournira, et pas de la version pdf (qui était juste pour
faciliter notre relecture papier crayon même si je me suis pas mal pris
la tête dessus). Dans la version actuelle, la biblio du html m'a bien
l'air découpée par chapitre donc je m'arrête là sauf si vous me dites ce
qui ne va pas. J'ai finalement utilisé un style de citation type chicago
style qui n'a pas l'air trop moche. Je crois que tes ISBN sont passés à
la trappe dans le html mais je dois avouer que je ne maîtrise pas très
bien l'export HTML. S'il y a besoin d'investiguer ça pour les faire
apparaître, je le ferai mais sinon pour l'instant, j'en reste là.

A+
    Arnaud

-- 
Basic, n.: A programming language. Related to certain social diseases in
that those who have it will not admit it in polite company.

**Comment by sabrinagranger** [comment]
@alegrand 
on rejoint l'issue #67 
la ventilation par chap est ok, mais la biblio finale par contre n'est pas au bon endroit : elle est actuellement à la suite des résumés au lieu d'être dans le chap dédié
sinon, pour les ISBN, c'est pas grave ; ce n'est pas un élément obligatoire pour citer les ressources
ok pour ce style inspiré de chicago manual of style
