### ISSUE TITLE
11.1 image tirée de Marwick

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#49]
(pb différent du pb d'affichage de la ref)

* contenu à corriger dir dans l'image svp 

Marwick, Ben, Carl Boettiger, et Lincoln Mullen. « Packaging Data Analytical Work Reproducibly Using R (and Friends) ». The American Statistician 72, nᵒ 1 (2 janvier 2018): 80‑88. https://doi.org/10.1080/00031305.2017.1375986.

data/my_data.csv : données primaires non modifiées 
--> svp mettre au féminin pluriel car actuellement au masculin pluriel ; merci !

**Comment by rougier** [comment]
Tu peux downloader l'image ici (je vois pas laquelle c'est). (drag and drop dans ta réponse)

**Comment by sabrinagranger** [comment]
ok mais ce sera en anglais, pas grave alors qu'il y avait eu cette démarche de traduction?les 2 me vont

**Comment by rougier** [comment]
C'est Elisa qui nous fait l'image. On a les sources mais pas les fontes. Faudrait lui demander si elle peut corriger (ça doit lui prendre 1 seconde, 2 max)

**Comment by sabrinagranger** [comment]
@elisadcg 
stp, pourrais-tu faire la modif? si tu n'as pas le temps, px-tu juste remplacer l'image par l'image originale stp? merci par avance
peut-on essayer de traiter ça avant mer stp?

**Comment by sabrinagranger** [comment]
![utas_a_1375986_f0001_b](https://user-images.githubusercontent.com/46864154/57232715-7ae98e80-701d-11e9-90a3-2c3a6e8b12fa.gif)

**Comment by sabrinagranger** [comment]
ai introduit dans le texte la version originale de l'image au cas où il n'y ait pas la VF de remplacement
on peut laisser tel quel dans le texte si jamais
