### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by borishejblum** [rr-france/bookrr#5]
Pour chaque solution, que pensez-vous d'un diagramme affichant les différents outils selon un niveau croissant de technicité pour aider le lecteur à se situer selon ses moyens ? 
 !! Peut être un peu lourd et/ou rébarbatif...
 !! Peut-être que la hierarchie est subjective et dépend de là ou on part ? -> confronter les points de vue de Loïc & Arnaud (nos 2 extrêmes ?)

**Comment by elisadcg** [comment]
J'entends cela non pas comme u diagramme (UML) mais plutôt comme un schéma qui présenterait au lecteur le niveau de difficulté (critère technique) pour comprendre et maîtriser les infos du chapitre.
Dans ce cas, pourquoi ne pas également prévoir un schéma sur le temps nécessaire à la mise en oeuvre du conseil. Et un autre sur l'importance de mise en place du changement ?
