### ISSUE TITLE
6.5 emplacement fig 6.1

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#50]
@alegrand dans le pdf, le schéma des dépendances matplotlib n'apparaît plus à la suite de ce texte "Lorsque l'on récupère l'ensemble des paquets nécessaires avec leurs dépendances, voici le graphe qu'on obtient, cf. Fig 6.1 (alerte paracétamol!). "
peut gêner la lecture

**Comment by alegrand** [comment]
Dans la version actuellement sur CI, c'est bon.
