### ISSUE TITLE
2;2, 2.3 etc. affichage html : alignement variable

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#53]
affichage version html
https://alegrand.github.io/bookrr/A-personas.html

quand il y a plus d'un paragraphe, il y a un changement de l'alignement : à gauche pour le 1er, puis à droite pour le second ; bizarre pour la lecture
ex 2.2, 2.3, 2.4
est-ce lié au style "citation"?

**Comment by alegrand** [comment]
Oui, le css du style "quote" fait ça. Je ne sais pas pourquoi et je n'y connais tellement rien en css que je n'ai pas trop le courage là. Si quelqu'un d'autre veut bien s'y coller...

**Comment by sabrinagranger** [comment]
ok, on laisse tomber, ce n'est pas majeur 
le pdf sort correctement aligné
