### ISSUE TITLE
Biblio: Perrin, Steve. 2019.

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#56]
Idem. L'année devrait être 2014.

**Comment by alegrand** [comment]
Comme pour les précédents, c'est mon sed qui est trop brutal et mélange pour year l'année de la consultation et l'année de production (il faut prendre l'un ou l'autre selon le type d'entrées). Je vais essayer de corriger ça asap.

**Comment by sabrinagranger** [comment]
yes, c'est bon dans les fichier .ref mais ça mélange les dates dans le texte (idem pour le Baker 2016 qui a changé de type de doc : on passe de l'article à la page web)

@article{perrinPreclinicalResearchMake2014,
	title = {Preclinical research : {Make} mouse studies work},
	volume = {507},
	shorttitle = {Preclinical research},
	url = {http://www.nature.com/news/preclinical-research-make-mouse-studies-work-1.14913},
	doi = {10.1038/507423a},
	abstract = {More investment to characterize animal models can boost the ability of preclinical work to predict drug effects in humans, says Steve Perrin.},
	language = {en},
	number = {7493},
	urldate = {2019-04-30},
	journal = {Nature News},
	author = {Perrin, Steve},
	month = mar,
	year = {2014},
	pages = {423},
	file = {Snapshot:C\:\\Users\\sgranger\\Zotero\\storage\\6VJ74KRL\\preclinical-research-make-mouse-studies-work-1.html:text/html}
}

**Comment by alegrand** [comment]
Ça devrait être bon maintenant grace au commit 29ac87d345dd9958e34f261faa5965185b6743ed.
