### ISSUE TITLE
Biblio: liens arXiv

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#58]
Il manque les liens vers les preprints arXiv...

**Comment by ppernot** [comment]
et Wikipedia

**Comment by sabrinagranger** [comment]
l'anomalie apparaît pour les refs dans le texte car les infos sont bien présentes dans le .refs
ça marchait avec le style entre crochets utilisé avant le 05/05

ex
@article{benureauRerunRepeatReproduce2017,
	title = {Re-run, {Repeat}, {Reproduce}, {Reuse}, {Replicate}: {Transforming} {Code} into {Scientific} {Contributions}},
	shorttitle = {Re-run, {Repeat}, {Reproduce}, {Reuse}, {Replicate}},
	url = {http://arxiv.org/abs/1708.08205},
	abstract = {Scientific code is not production software. Scientific code participates in the evaluation of a scientific hypothesis. This imposes specific constraints on the code that are often overlooked in practice. We articulate, with a small example, five characteristics that a scientific code in computational science should possess: re-runnable, repeatable, reproducible, reusable and replicable.},
	urldate = {2017-09-25},
	journal = {arXiv:1708.08205 [cs]},
	author = {Benureau, Fabien and Rougier, Nicolas},
	month = aug,
	year = {2017},
	note = {arXiv: 1708.08205},
	keywords = {Computer Science - Computers and Society, Computer Science - General Literature, lu},
	file = {arXiv\:1708.08205 PDF:C\:\\Users\\sgranger\\Zotero\\storage\\E2CXNH7I\\Benureau et Rougier - 2017 - Re-run, Repeat, Reproduce, Reuse, Replicate Trans.pdf:application/pdf;arXiv.org Snapshot:C\:\\Users\\sgranger\\Zotero\\storage\\88R4JJ6S\\1708.html:text/html}
}

**Comment by alegrand** [comment]
Normalement, c'est bon maintenant. Réouvrez si ça n'est pas le cas.
