### ISSUE TITLE
Import Zotero depuis page html

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#61]
quand on importe les refs biblios depuis la page 
https://alegrand.github.io/bookrr/

qqs soucis :
* les noms des auteurs sont tous dans le même champ "auteur" ; il faudrait 1 nom/ champ car il est répétable
* le titre répercuté est "Livre d’introduction à la recherche reproductible rédigé lors d’un * booksprint" au lieu du titre réel
* champs qui pourraient être comblés ; éd. Urfist de Bordeaux , date : 2019 ; lieu Bordeaux ; ISBN 979-10-97595-05-0 (ISBN pour l'éd numérique ; l'éd imprimée dispose d'un autre ISBN)

**Comment by sabrinagranger** [comment]
je px voir avec des collègues pour traiter ce point si besoin

**Comment by alegrand** [comment]
Oui, alors là aucune idée. Je ne sais pas comment zotero fonctionne.

**Comment by sabrinagranger** [comment]
ok, j'ai des experts sous la main, je vais leur soumettre ça
