### ISSUE TITLE
modalités de contribution : pull request ou issue? pb cohérence

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#63]
pb 2 manières différentes de contribuer sont proposées 

dans le readme, on dit de proposer des issues
dans les annexes, on parle de pull request

quel choix fait-on? svp?

**Comment by ppernot** [comment]
Issues: on ne va pas demander aux contributeurs de créer leur branche.

**Comment by sabrinagranger** [comment]
merci ! modifié
