### ISSUE TITLE
disparition des refs biblios dans le texte??

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#64]
@alegrand 
bizarre, toutes les refs biblios citées semblent avoir disparu alors que le fichier .refs est tjs complet
est-ce lié à cette opération?
	Use perl instead of sed to make a better job with bib processing.

exemple
"La crise de la reproductibilité de la science est aujourd’hui un phénomène mondial et largement transdiciplinaire qui concourt à la défiance de la société à l’égard du monde de la recherche (???). Le sujet est ancien, mais la situation semble avoir atteint un point critique. Des études ont par exemple démontré qu’il n’était pas possible d’obtenir de nouveau les résultats d’études pré-cliniques ou cliniques (???) (???). Si la reproductibilité des résultats ne peut être considérée comme seul critère de la scientificité d’une recherche, cette crise suscite des interrogations au sein même de la communauté scientifique."

**Comment by alegrand** [comment]
Oui, je sais. Désolé, c'est temporaire. Je suis dessus. C'est la joie du "ça marchait chez moi" mais "ça marche pas là-bas).

**Comment by sabrinagranger** [comment]
c'est tout beau maintenant !! merci Arnaud

**Comment by alegrand** [comment]
Voilà, problème en partie corrigé. Il reste que les url et les isbn n'apparaissent maintenant plus dans le html alors qu'ils apparaissent bien dans le pdf. :(

**Comment by sabrinagranger** [comment]
@borishejblum 
on attend ton feu vert avec Elisa , j'ai fini mon tour

**Comment by borishejblum** [comment]
OK, on finit de traiter le chap 1 et je vous donne le feu vert avant lundi. Dans l'idéal, il faudrait fermer toutes les issues qui ne sont pas lié à des problèmes techniques (eg compilation bookdown) d'ici là

**Comment by alegrand** [comment]
@borishejblum  . Pourquoi cette issue a-t-elle été réouverte ? Il me semble que la biblio est OK. Les URLs et les DOI apparaissent bien partout. Il n'y a que les ISBN mais c'est discuté dans l'issue #67.

**Comment by sabrinagranger** [comment]
pour ma part, c'est ok, mais j'ai peut-être raté qq chose pour cette issue? 
@borishejblum : ven, quand vous aurez fini la révision du chap sur les defs, je repasserai un petit coup 
vuos embêtez pas avec la biblio s'il y en a ; un DOI dans le corps de texte fera mon bonheur

**Comment by borishejblum** [comment]
OK au temps pour moi je referme l'issue alors, je n'avais pas fait le lien avec #67
