### ISSUE TITLE
Problème de date dans refs.bib

### ISSUE THREAD

**Issue by alegrand** [rr-france/bookrr#66]
Vangeance! ;-) @sabrinagranger : dans ton zotero, les year pour les webinars sont incorrects.

```
misc{legrandSeriesWebinarsDocuments2019,`
        title = {Series of webinars and documents on {Reproducible} {Research} - {Controling} your environment},
        shorttitle = {Series of webinars and documents on {Reproducible} {Research}},
        url = {https://github.com/alegrand/RR_webinars/blob/master/2_controling_your_environment/index.org},
        urldate = {2019-04-30},
        journal = {Reproducible Research Webinars},
        author = {Legrand, Arnaud},
        month = apr,
        year = {2019},
        note = {original-date: 2016-02-08T08:41:51Z}
}

```
Le year, c'est 2016 du coup mais il est stoqué dans note. Là, ça devient pénible de distinguer à coup de script s'il faut que je fasse confiance au year ou au note donc je veux bien que tu corriges de ton côté.

**Comment by sabrinagranger** [comment]
argh le coup de couteau vient tjs des proches ! 
ok, je vais corriger
c'est qd même pénible ce mix avec la date de consultation :\

**Comment by sabrinagranger** [comment]
@sabrinagranger : modifier les clés de citation dans le texte

**Comment by sabrinagranger** [comment]
clés de citation maj dans le texte
vérif exemple https://alegrand.github.io/bookrr/C-data-share.html
pour le moment, ref dans le texte non trouvée (affichage html)


@misc{legrandSeriesWebinarsDocuments2016,
	title = {Series of webinars and documents on {Reproducible} {Research} - {Controling} your environment},
	shorttitle = {Series of webinars and documents on {Reproducible} {Research}},
	url = {https://github.com/alegrand/RR_webinars/blob/master/2_controling_your_environment/index.org},
	urldate = {2019-04-30},
	journal = {Reproducible Research Webinars},
	author = {Legrand, Arnaud},
	month = feb,
	year = {2016},
	note = {original-date: 2016-02-08T08:41:51Z}

**Comment by sabrinagranger** [comment]
@alegrand 
tout va bien il me semble? on peut fermer l'issue?

**Comment by alegrand** [comment]
Oui, ça m'a l'air nickel.

**Comment by sabrinagranger** [comment]
![happiness](https://user-images.githubusercontent.com/46864154/57441588-91c0f880-724a-11e9-887e-43ae2182db6a.jpg)
