### ISSUE TITLE
Biblio finale dans 4e de couverture (html)

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#67]
dans la version html, la biblio finale a fichu le camp dans la 4ème de couverture ! (et ne figure plus dans https://alegrand.github.io/bookrr/bibliographie.html) 

https://alegrand.github.io/bookrr/quatrieme-de-couverture.html

Quatrième de couverture
[...]

With this book, students and engineers and researchers should find efficient and accessible ways leading them to improve their reproducible research practices."

Abelson, Harold, Gerald Jay Sussman, Julie Sussman, and Alan J. Perlis. 1996. Structure and Interpretation of Computer Programs. Cambridge, Etats-Unis d’Amérique: MIT Press.

Adlin, Tamara, and John Pruitt. 2010. The Essential Persona Lifecycle: Your Guide to Building and Using Personas. Elsevier. doi:10.1016/C2009-0-62475-2.

Arnal, Florent, Lionel Bombrun, Jean-Pierre Da Costa, Cécile Dantzer, Robin Genuer, Marthe-Aline Jutand, Marie Lebreton, Sébastien Moutault, Jérôme Saracco, and Raphaëlle Savoire. 2019. “BeginR.” Begin’R. http://beginr.u-bordeaux.fr/.

Arnold, Douglas N. 2000. “The Patriot Missile Failure.” Douglas N. Arnold McKnight, Presidential Professor of Mathematics. http://www-users.math.umn.edu/~arnold/disasters/patriot.html.

Baker, Monya. 2016. “1,500 Scientists Lift the Lid on Reproducibility.” Nature 533 (7604): 452–54. doi:10.1038/533452a.

Baker, Rachel, David Berry, Mark Brokering, Michael Dieter, Amanda French, and Barbara Rühling. 2014. On Book Sprints. Berlin: Booksprints.net. https://www.booksprints.net/en/blog/book-sprint-on-book-sprints/.

**Comment by alegrand** [comment]
Argh! J'avais vu qu'elle avait disparue mais comme elle apparaissait au fur et à mesure des chapitres, ça me semblait OK. Je n'avais pas vu qu'elle avait fichu le camp dans la 4ème de couverture! Cochonnerie de bookdown/pandoc tout opaque. Je regarde de ce pas et je vous tiens au courant.

**Comment by alegrand** [comment]
J'ai enfin résolu le problème dans 9769c3b6ff5c3da1d0f7d82c7fca8731edaf7cc1. Ma première expérience du debuger R (qui est incroyablement pourri comparé à gdb!).
