### ISSUE TITLE
Mention du book sprint dans version imprimée? 

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#68]
Svp, je vous propose que les modalités de rédaction (i.e book sprint) soient indiquées au fil de la version imprimée de manière courte et discrète (ex sur la pages impaires ou autre)

ces modalités de rédaction étant très spécifiques, cela me semble une info à donner au lecteur

si ça ne vous enchante pas, envoyez-moi vos sms surtaxés avant le 10/05

**Comment by borishejblum** [comment]
Je suis d'accord c'est une info importante. Mais n'est-ce pas un peu lourd de l'afficher partout ?

**Comment by sabrinagranger** [comment]
je pensais à une mention en bas de page ou haut de page (en fonction de ce qu'Elisa conseillera)
ex : Livre issu d'un book sprint

comme les lecteurs peuvent naviguer d'un chap à l'autre, et qu'à part les fans hard core, ils n'iront pas lire les annexes, c'est la solution qui me semblait la + adaptée

**Comment by alegrand** [comment]
Moui, comme @borishejblum le mentionner aussi régulièrement me parait un peu lourd. En rappelant "toutes les pages" que c'est issu d'un book sprint, les gens pourraient y voir une excuse pour un document de piètre qualité, ce qui n'est pas le cas. 

Ceci étant dit, je comprends qu'on souhaite faire la pub du concept du book sprint et que les lecteurs soit conscients du mode de réalisation de notre ouvrage. Comme actuellement c'est uniquement mentionné dans les annexes, les lecteurs risquent de passer complètement à côté.  Je suis peut-être de l'ancienne école mais moi, la première chose que je fais avec feuilleter le livre pour voir s'il m'atire, c'est lire le préembule et la 4ème de couverture. Je pense donc que ça devrait être mentionné dans le préembule et renvoyer vers l'annexe pour ceux qui veulent en savoir plus.

**Comment by loicdesquilbet** [comment]
Ok pour moi pour ne le mentionner que dans le préambule (+éventuellement sur la 4ème page de couverture), avec renvoi vers l'annexe.

**Comment by sabrinagranger** [comment]
comme disent les cool kids, banco pour la mention dans le préambule avec renvoi vers l'annexe et la 4ème de couverture
merci !
