### ISSUE TITLE
Table des matières is missing (pdf)

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#69]
@alegrand 
tu vas me maudire - je viens de voir que la table des matières a disparu quand on fait un export pdf depuis bookdown (une autre mauvaise nvelle d'ailleurs dans une autre issue)

**Comment by alegrand** [comment]
C'est bon elle est revenue. Il y avait un problème de compilation, du coup, le .tex n'était compilé qu'une fois au lieu de 3 pour régler toutes les questions de références croisées et la table des matières était mal insérées.
