### ISSUE TITLE
Epub fail

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#70]
@alegrand 
maxima culpa car je n'avais pas testé avant
l'export Epub ne marche pas du tout, mais peut-être est-ce normal car temporaire? 

https://alegrand.github.io/bookrr/booksprintrr.epub
File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

**Comment by borishejblum** [comment]
je pense que c'est normal et que pour l'instant aucune sortie au format epub n'est générée. Ça ne me semble pas urgent

**Comment by sabrinagranger** [comment]
ok de l'anormal normal donc
bonne nvelle alors
merci !

**Comment by alegrand** [comment]
C'est bon. La génération de l'epub était cassée et il n'était plus propagé. Comme mon script de build est cochon, il ne m'indiquait pas que le build avait échoué. Sorry.
