### ISSUE TITLE
Accents aigus rubrique "Références"? 

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#76]
@alegrand 
désolée, je l'ai vu au moment du travail sur la mise en page : stp, serait-il possible de mettre les accents aigus du sous-titre "Références" qui introduit les biblios de fin de chapitre? 
merci par avance pour ton aide

**Comment by sabrinagranger** [comment]
je ne vois plus la rubrique
mais on peut aussi s'en tenir à cela

**Comment by borishejblum** [comment]
Que veux-tu dire  @sabrinagranger ? La rubrique apparait bien en fin de chapitre
