### ISSUE TITLE
Pb mode édition depuis https://rr-france.github.io/bookrr/

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#77]
svp, l'un de vous pourrait-il changer les liens pour que le mode édition fonctionne depuis cette page? 
https://rr-france.github.io/bookrr/
actuellement, ça renvoie vers un message d'erreur
si c'était possible **d'ici lundi 03/06** ... ça m'arrangerait bien ... (je paie en pâté de canard)
merci par avance !

**Comment by ppernot** [comment]
C'est compliqué, les fichiers github sont des .md, le bookdown pointe vers les .Rmd générés par le script d'Arnaud. Puis faut ajouter '/src' dans le path...
Trop fort pour moi...

**Comment by sabrinagranger** [comment]
beuh, ça marche pas pour moi?? je viens de tester
tjs le même message d'erreur : page non trouvée

**Comment by borishejblum** [comment]
il manque le _src_ dans l'url juste avant le nom du fichier

**Comment by borishejblum** [comment]
j'ai fait le changement dans le fichier `_output.yml`
@sabrinagranger si c'est bon tu peux fermer l'issue

**Comment by borishejblum** [comment]
OK c'est bon ça marche

**Comment by sabrinagranger** [comment]
merci Boris
mais par contre, n'importe quel utilisateur github pourra éditer le texte directement ou c'est parce que j'ai des droits spécifiques sur l'entrepôt?

**Comment by sabrinagranger** [comment]
je pensais qu'on pouvait gérer des nivx d'autorisations

**Comment by sabrinagranger** [comment]
@borishejblum j'ai honte mais ça me turlupine depuis tout à l'heure : je pensais vraiment pas que n'importe quel utilisateur pouvait d'emblée modifier les textes ; stp, est-ce qu'on peut finalement désactiver la fonctionnalité? toutes mes excuses les plus plates d'avoir ft la demande sans anticiper les conséquences

**Comment by borishejblum** [comment]
non c'est simplement parce que toi tu es **connectée** ET tu as les **droits**. Mais, en plus d'être pratique pour nous pour corriger les typos qui pourraient encore trainer, ça encourage et facilite les pull requests :-)

**Comment by borishejblum** [comment]
Seuls les contributeurs autorisés peuvent commiter sur le repertoire github. Les autres doivent passer par le système des _pull request_

**Comment by sabrinagranger** [comment]
ah ouf ! merci Boris et mes excuses pour le message d'angoisse ; pârfait
