### ISSUE TITLE
6.5 : insérer avec la bonne syntaxe la légende image 6.1?? 

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#78]
ai tenté la syntaxe : 
![Légende](url vers l'image)

mais le texte ""Exemple des dépendances de la bibiliothèque python matplotlib — obtenu avec debtree”" ne s'affiche pas (bravo hein)

plutôt que de tout pourrir, j'ai enlevé mon truc et préfère passer la main svp

j'ai fait un ajout dans le texte :
La figure 6.1 “Exemple des dépendances de la bibliothèque python matplotlib — obtenu avec debtree” (alerte paracétamol) permet de voir le graphe obtenu lorsque l’on récupère l’ensemble des paquets nécessaires avec leurs dépendances. 

mais ce serait bien avec une vraie légende car le schéma sera sur une page à part dans le fichier final

**Comment by sabrinagranger** [comment]
si c'était possible de le faire d'ici le 03/06 ou dans le courant de cette 1re semaine de juin, ça permettrait de transmettre ça à Elisa avec le lot des autres demandes svp

**Comment by ppernot** [comment]
J'ai ajouté fig_caption: true dans bookdown.yml.
Faut voir si ça marche...

**Comment by sabrinagranger** [comment]
mince, je suis total saucisse mais je vois rien : ni sur la version 
https://rr-france.github.io/bookrr/B-code-aspect.html#lenvironnement-de-calcul-ou-le-paradigme-des-poupees-russes-diaboliques
ni en générant le pdf :\

**Comment by ppernot** [comment]
Faut touver autre chose, alors :-(
Je tente de la rajouter dans output.yml ...

**Comment by ppernot** [comment]
I attempted to use a R chunk to display the fig.
This crashed the compilations because of a missing package...

**Comment by ppernot** [comment]
Pb. solved :-)

**Comment by sabrinagranger** [comment]
génial Pascal !! merci :)
