### ISSUE TITLE
1 - Etat des lieux

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#8]
* Sect. 1.2: 'Par exemple, ne serait-ce parce que' très lourd. Je remplacerais par 'De fait,'
* Sect. 1.2: " il s'agit" --> 'il s'agira"
* Sect. 1.2: "résultat bit pour bit" --> "résultat numérique bit pour bit"
* Sect. 1.2: Introduire un nouveau paragraphe au niveau de "L'expression"
* Sect. 1.2: "incluant, mais n'étant pas limitées" --> "incluant, sans y être limitées"

* Sect. 1.5: "La possibilité" --> "L'impossibilité"
* Sect. 1.5: "patient zéro" ??? expliquer...
* Sect. 1.5: nouveau paragraphe à "Au travers"

* Sect. 1.6: "La minute théologie négative" ??? expliquer...  
* Sect. 1.6: "Randall et Wesler" --> ajouter citation
* Sect. 1.6: "sur-interptéter le résultat" --> "sur-interpréter un résultat"
* Sect. 1.6: "cités supra" --> supprimer
* Sect. 1.6: "se documenter" --> "se référer à la litérature"

**Comment by sabrinagranger** [comment]
Sect. 1.2: 'Par exemple, ne serait-ce parce que' très lourd. Je remplacerais par 'De fait,' : fait
Sect. 1.2: " il s'agit" --> 'il s'agira" : fait
Sect. 1.2: "résultat bit pour bit" --> "résultat numérique bit pour bit" : fait
Sect. 1.2: Introduire un nouveau paragraphe au niveau de "L'expression" : fait
Sect. 1.2: "incluant, mais n'étant pas limitées" --> "incluant, sans y être limitées" : "ce travail incluant, sans s'y limiter,"
Sect. 1.5: "La possibilité" --> "L'impossibilité" : fait
Sect. 1.5: "patient zéro" ??? expliquer... : supprimé
Sect. 1.6: "sur-interptéter le résultat" --> "sur-interpréter un résultat" : fait
Sect. 1.6: "cités supra" --> supprimer : remplacé par "Pour tous ces sujets cités précédemment"
Sect. 1.6: "se documenter" --> "se référer à la littérature" : fait
