### ISSUE TITLE
Coquille titre version html

### ISSUE THREAD

**Issue by sabrinagranger** [rr-france/bookrr#82]
Spotté par une collègue au regard de lynx : une coquille "Vers une recherche reproducible"
cf capture ci-dessous
mais je ne sais pas où corriger ça :\ 
merci par avance ! 
![coquille](https://user-images.githubusercontent.com/46864154/59345514-94fb4880-8d10-11e9-8525-290f23efefd3.png)

**Comment by borishejblum** [comment]
J'ai corrigé, c'est dans le fichier _output.yml

**Comment by sabrinagranger** [comment]
merci Boris ! :)
