### ISSUE TITLE
2 - Retours d'expếrience

### ISSUE THREAD

**Issue by ppernot** [rr-france/bookrr#9]
* Par. 1: "fictifs" 2 fois de suite. Peut-être "fictionnels" pour le 2ème ?

* Sect. 2.3: "C'est assez un travail" --> "C'est un travail"

**Comment by borishejblum** [comment]
- Retirer "(traumatiques)" du titre (il me semble que ces retours d'expériences) ne sont plus réellement traumatisants, si ?

**Comment by sabrinagranger** [comment]
Retirer "(traumatiques)" : fait
Par. 1: "fictifs" 2 fois de suite. Peut-être "fictionnels" pour le 2ème ? --> 
"Il s'agit de personnages inventés mais néanmoins vraisemblables car inspirés d'expériences réelles. "
Sect. 2.3: "C'est assez un travail" --> "C'est un travail" : fait
